apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-svc
spec:
  selector:
    app: {{ include "myapp.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
