{
 "title": "MyApp - Overview",
 "tags": [
  "myapp",
  "auto-generated"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests / sec (5m rate)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total{app=\"myapp\"}[5m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "5xx Error Rate (%) (5m)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ( sum(rate(myapp_http_requests_total{app=\"myapp\",http_status=~\"5..\"}[5m])) / (sum(rate(myapp_http_requests_total{app=\"myapp\"}[5m])) + 1e-9) )",
     "legendFormat": "5xx % (5m)"
    }
   ]
  },
  {
   "title": "P95 latency (s)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(myapp_request_latency_seconds_bucket{app=\"myapp\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Last  /health status (200=ok)",
   "type": "singlestat",
   "gridPos": { "x": 6, "y": 6, "w": 6, "h": 4 },
   "format": "none",
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"myapp-svc\", namespace=\"default\"}[5m])"
    }
   ]
  },
  {
   "title": "Recent 5xx count (by endpoint)",
   "type": "table",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 4 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(myapp_http_requests_total{app=\"myapp\",http_status=~\"5..\"}[5m]))"
    }
   ]
  }
 ]
}