replicaCount: 1
image:
  repository: "192.168.86.75:80/library/myapp"
  tag: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
