name: ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, docker]
    env:
      IMAGE_REPO: 192.168.86.75:80/library/myapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python venv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f apps/myapp/requirements.txt ]; then
            pip install -r apps/myapp/requirements.txt
          fi

      - name: Run unit tests
        run: |
          . venv/bin/activate
          python -m unittest discover || true

      - name: Docker login to Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USER }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
        run: |
          if [ -z "$HARBOR_USER" ] || [ -z "$HARBOR_PASS" ]; then
            echo "HARBOR_USER/HARBOR_PASS not set; aborting"
            exit 1
          fi
          echo "$HARBOR
