name: ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, docker]
    env:
      IMAGE_REPO: 192.168.86.75:80/library/myapp
    steps:
      # Checkout 使用 SSH
      - name: Checkout repository via SSH
        uses: actions/checkout@v4
        with:
          repository: LumosNebula/devops-project
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          fetch-depth: 0

      # 设置 Python 虚拟环境
      - name: Setup Python venv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f apps/myapp/requirements.txt ]; then pip install -r apps/myapp/requirements.txt; fi

      # 运行单元测试
      - name: Run unit tests
        run: |
          . venv/bin/activate
          python -m unittest discover || true

      # Docker 登录 Harbor
      - name: Docker login to Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USER }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
        run: |
          if [ -z "$HARBOR_USER" ] || [ -z "$HARBOR_PASS" ]; then
            echo "HARBOR_USER/HARBOR_PASS not set; aborting"
            exit 1
          fi
          echo "$HARBOR_PASS" | docker login 192.168.86.75:80 -u "$HARBOR_USER" --password-stdin

      # Build & Push 镜像
      - name: Build and push Docker image
        id: build-image
        run: |
          set -e
          IMAGE_TAG=$(git rev-parse --short=12 HEAD)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          docker build -t ${IMAGE_REPO}:${IMAGE_TAG} -f apps/myapp/Dockerfile apps/myapp
          docker push ${IMAGE_REPO}:${IMAGE_TAG}

      # 更新 Helm values 并推回 GitHub
      - name: Update Helm values and push
        env:
          CI_GIT_TOKEN: ${{ secrets.CI_GIT_TOKEN }}
          REPO: ${{ github.repository }}
          IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
        run: |
          if [ -z "$CI_GIT_TOKEN" ]; then
            echo "CI_GIT_TOKEN not set; skipping Helm values update"
            exit 0
          fi
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${CI_GIT_TOKEN}@github.com/${REPO}
          git fetch origin
          git checkout -B main
          sed -i "s|tag: .*|tag: ${IMAGE_TAG}|" charts/myapp/values.yaml
          git add charts/myapp/values.yaml
          git commit -m "ci: update image tag to ${IMAGE_TAG}" || echo "no changes to commit"
          git push origin main

      # Trigger ArgoCD sync
      - name: Trigger ArgoCD sync
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          if [ -z "$ARGOCD_SERVER" ] || [ -z "$ARGOCD_TOKEN" ]; then
            echo "ARGOCD_SERVER or ARGOCD_TOKEN not set; skipping ArgoCD sync"
            exit 0
          fi
          APP_NAME="myapp"
          curl -k -X POST -H "Authorization: Bearer ${ARGOCD_TOKEN}" "${ARGOCD_SERVER}/api/v1/applications/${APP_NAME}/sync" || true

      # 可选：直接 apply manifests
      - name: Apply manifests via Kubeconfig
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}
        run: |
          if [ -z "$KUBECONFIG_B64" ]; then
            echo "KUBECONFIG not provided; skipping kubectl apply"
            exit 0
          fi
          echo "${KUBECONFIG_B64}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl get nodes -o wide
          kubectl apply -f manifests/ || true

      #  输出最终状态
      - name: Final status
        run: |
          echo "Image pushed: ${IMAGE_REPO}:${{ steps.build-image.outputs.IMAGE_TAG }}"
          kubectl --kubeconfig=/var/jenkins_home/.kube/config get pods -l app=myapp -n default -o wide || true
          sed -n '1,160p' charts/myapp/values.yaml || true
