name: ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, docker]
    env:
      IMAGE_REPO: harbor.local:30003/library/myapp

    steps:
      # Checkout 仓库，用 SSH Deploy Key
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: LumosNebula/devops-project
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          fetch-depth: 0

      # Setup Python venv 
      - name: Setup Python virtual environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f apps/myapp/requirements.txt ]; then
            pip install -r apps/myapp/requirements.txt
          fi

      # Run unit tests
      - name: Run unit tests
        run: |
          . venv/bin/activate
          python -m unittest discover || true

      # Docker login to Harbor
      - name: Docker login to Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USER }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
        run: |
          if [ -z "$HARBOR_USER" ] || [ -z "$HARBOR_PASS" ]; then
            echo "HARBOR_USER/HARBOR_PASS not set; aborting"
            exit 1
          fi
          echo "$HARBOR_PASS" | docker login harbor.local:30003 -u "$HARBOR_USER" --password-stdin

      #  Build & push Docker image
      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=$(git rev-parse --short=12 HEAD)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          docker build -t ${IMAGE_REPO}:${IMAGE_TAG} -f apps/myapp/Dockerfile apps/myapp
          docker push ${IMAGE_REPO}:${IMAGE_TAG}

      #  Update Helm chart values & push back using SSH
      - name: Update Helm chart image tag
        run: |
          IMAGE_TAG=${{ steps.build-image.outputs.IMAGE_TAG }}
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout -B main
          sed -i "s|tag: .*|tag: ${IMAGE_TAG}|" charts/myapp/values.yaml
          git add charts/myapp/values.yaml
          git commit -m "ci: update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push origin main

      #  Trigger ArgoCD sync
      - name: Trigger ArgoCD sync
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          if [ -z "$ARGOCD_SERVER" ] || [ -z "$ARGOCD_TOKEN" ]; then
            echo "ARGOCD_SERVER or ARGOCD_TOKEN not set; skipping ArgoCD sync"
            exit 0
          fi
          APP_NAME="myapp"
          curl -k -X POST -H "Authorization: Bearer ${ARGOCD_TOKEN}" \
            "${ARGOCD_SERVER}/api/v1/applications/${APP_NAME}/sync" || true

      # Apply manifests via kubeconfig 
      - name: Apply manifests via kubeconfig
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}
        run: |
          if [ -z "$KUBECONFIG_B64" ]; then
            echo "KUBECONFIG not provided; skipping kubectl apply"
            exit 0
          fi
          echo "${KUBECONFIG_B64}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl get nodes -o wide
          kubectl apply -f manifests/ || true

      #  Final status  
      - name: Final status
        run: |
          echo "Image pushed: ${IMAGE_REPO}:${{ steps.build-image.outputs.IMAGE_TAG }}"
          kubectl --kubeconfig=/var/jenkins_home/.kube/config get pods -l app=myapp -n default -o wide || true
          sed -n '1,160p' charts/myapp/values.yaml || true
